[platformio]
src_dir = .

[env:adafruit_matrixportal_esp32s3]
platform = espressif32
board = adafruit_matrixportal_esp32s3
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>
lib_deps =
    https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git
    adafruit/Adafruit GFX Library
